running setup... SQLAlchemy Engine URL is sqlite:////home/thebuleganteng/MyFinance50_public/finance.sqlite
running setup... db.create_all has run
running update_listings ... PINGING API
running setup... SQLAlchemy Engine URL is sqlite:////home/thebuleganteng/MyFinance50_public/finance.sqlite
running setup... db.create_all has run
running update_listings ... PINGING API
running setup... SQLAlchemy Engine URL is sqlite:////home/thebuleganteng/MyFinance50_public/finance.sqlite
running setup... db.create_all has run
PING COUNTER: 1
running purge_unconfirmed_accounts ... started: 2024-01-30 09:05:05.349387
running setup... SQLAlchemy Engine URL is sqlite:////home/thebuleganteng/MyFinance50_public/finance.sqlite
running setup... db.create_all has run
PING COUNTER: 1
running purge_unconfirmed_accounts ... started: 2024-01-31 09:05:11.595221
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 10, in <module>
    from forms.forms import BuyForm, LoginForm, PasswordChangeForm, PasswordResetRequestForm, PasswordResetRequestNewForm, ProfileForm, QuoteForm, RegisterForm, SellForm
  File "/home/thebuleganteng/MyFinance50_public/forms/forms.py", line 15, in <module>
    class FilterTransactionHistory(FlaskForm):
  File "/home/thebuleganteng/MyFinance50_public/forms/forms.py", line 17, in FilterTransactionHistory
    start_time = TimeField('Start Time', format='%H:%M', default=lambda:datetime.now())
NameError: name 'TimeField' is not defined. Did you mean: 'DateField'?
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 14, in <module>
    from helpers import apology, company_data, date_time, fmp_key, generate_nonce, generate_unique_token, login_required, lookup, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, send_email, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
Traceback (most recent call last):
  File "/home/thebuleganteng/MyFinance50_public/scripts/listings_update.py", line 8, in <module>
    from app import create_app
  File "/home/thebuleganteng/MyFinance50_public/app.py", line 5, in <module>
    from helpers import apology, Babel, base64, build, check_password_hash, company_data, datetime, date_time, EmailMessage, fmp_key, format_decimal, func, generate_nonce, generate_password_hash, generate_unique_token, logging, login_required, Migrate, number_format, or_, os, percentage, Portfolio, process_purchase, process_sale, project_name, process_user_transactions, re, RotatingFileHandler, send_email, Session, setup_logging, sys, time, unquote, update_listings, usd, verify_unique_token
ImportError: cannot import name 'apology' from 'helpers' (/home/thebuleganteng/MyFinance50_public/MyFinance50-env/lib/python3.10/site-packages/helpers/__init__.py)
